
export const ADD_BUCKET_SUCCESS = 'ADD_BUCKET_SUCCESS';
export const ADD_BUCKET_FAILED = 'ADD_BUCKET_FAILED';

export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';

export const SET_BUCKET_SUCCESS = 'SET_BUCKET_SUCCESS';
export const SET_BUCKET_FAILED = 'SET_BUCKET_FAILED';

export const RESET_ERROR = 'RESET_ERROR';
export const SET_ERROR = 'SET_ERROR';


export const SET_SELECTED_BUCKET = 'SET_SELECTED_BUCKET';
export const RESET_SELECTED_BUCKET = 'RESET_SELECTED_BUCKET';

export const SET_TODO_SUCCESS = 'SET_TODO_SUCCESS';
export const SET_TODO_FAILED = 'SET_TODO_FAILED';

export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FAILED = 'UPDATE_TODO_FAILED';

export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILED = 'DELETE_TODO_FAILED';




